public class PETwo
{

	/*

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	find the sum of the even-valued terms.

	*/

	public static void main(String[] args)
	{

		Long a, b, c, cutoff, answer;

		a = 1L;
		b = 2L;
		c = 0L;
		answer = 0L;

		cutoff = 4000000L;

		while ((a < cutoff) && (b < cutoff) && (c < cutoff))
		{

			if (a % 2 == 0) 
			{ 
				answer += a; 
			}

			if (b % 2 == 0)
			{
				answer += b;
			}

			if (c % 2 == 0)
			{
				answer += c;
			}

			c = a + b;
			a = b + c;
			b = a + c;

		}

		System.out.println(answer);

	}

}